DinucMVC/DinucMVC/Models/Dinucleotide.cs
using System;

namespace DinucMVC.Models
{
    public class Dinucleotide
    {
        public string Dinuc { get; set; }
        public int Dinuc1st { get; set; }
        public int Dinuc2nd { get; set; }
        public double Dinuc1stFrq { get; set; }
        public double Dinuc2ndFrq { get; set; }
    }


}

DinucMVC/DinucMVC/Models/DinucleotidesList.cs
using System;
using System.Collections.Generic;

namespace DinucMVC.Models
{
    public class DinucleotidesList
    {
        public List<Dinucleotide> DinucFrq { get; set; }
    }
}

DinucMVC/DinucMVC/Models/Sequence.cs
namespace DinucMVC.Models
{
    public class Sequence
    {
        public string Seq { get; set; }
        public int SeqLength { get; set; }
    }
}

DinucMVC/DinucMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

//namespace DinucMVCMono.Controllers
namespace DinucMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            //ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            //ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            ViewBag.SeqCorrect = "true";

            return View("~/Views/Home/SeqInput.cshtml");
        }

        public ActionResult About()
        {

            return View();
        }

        public ActionResult Contacts()
        {

            return View();
        }

    }
}

DinucMVC/DinucMVC/Controllers/SeqController.cs
using System.Web.Mvc;
using DinucCalculation;
using DinucMVC.Helpers;
using DinucMVC.Models;

namespace DinucMVC.Controllers
{

    public class SeqController : Controller
    {
        [HttpPost]
        public ActionResult SeqInput(string seq)
        {
            Match match = new Match();
            if (match.MatchNuc(seq))
            {
                Sequence sequence = new Sequence
                {
                    Seq = seq,
                    SeqLength = seq.Length
                };

                SeqOutput seqOutput = new SeqOutput(sequence);
                ViewBag.SeqLength = sequence.SeqLength;
                ViewBag.SeqOutput = seqOutput.SeqOut();

		//Dinucleotide calculation
		DinucCalc dinucCalc = new DinucCalc(sequence.Seq);
		var dinucList = dinucCalc.GetDinucleotides();

                return View("~/Views/Seq/SeqCalc.cshtml");
            }
            else
            {
                ViewBag.SeqCorrect = "false";
                //MessageBox.Show("ACGT only!");
                return View("~/Views/Home/SeqInput.cshtml");
            }
        }
    }
}

DinucMVC/DinucMVC/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>About</title>
</head>
<body>
        <h2>In About View</h2>
</body>
</html>


DinucMVC/DinucMVC/Views/Home/Contacts.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>Contacts</title>
</head>
<body>
</body>
</html>


DinucMVC/DinucMVC/Views/Home/Index.cshtml
<h2>Welcome to ASP.NET MVC @ViewData["Version"] on @ViewData["Runtime"]!</h2>

DinucMVC/DinucMVC/Views/Home/SeqInput.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
        <title>Enter Sequence</title>
</head>
<div class="container">
        <div class="row justify-content-center row-gap-top-40">
                <h2>Enter sequence</h2>
        </div>
        <div class="row justify-content-center row-gap-top-10">
                @if(ViewBag.SeqCorrect == "true"){
                        <p style="color: black">Enter A, C, G, T or a, c, g, t only, no gaps in between.</p>
                }
                else{
                        <p style="color: red">Enter A, C, G, T or a, c, g, t only, no gaps in between. Try again.</p>
                }
                
        </div>               
        @using(Html.BeginForm("SeqInput", "Seq", FormMethod.Post))
        {
                <div class="row justify-content-center row-gap-top-10">
                              @Html.TextArea("seq", new{placeholder="AGAGACAGATGGACGG...", @class="txt-area"})
                </div>
                <div class="row justify-content-center row-gap-top-10">
                        <button class="btn-size">Calculate</button>
                </div>
        }
</div>

DinucMVC/DinucMVC/Views/Seq/SeqCalc.cshtml
@{
    Layout ="~/Views/Shared/_Layout.cshtml";
    var sqLength = ViewBag.SeqLength;
    var sqOut = ViewBag.SeqOutput;
}

<body>
        <div class="container">
                <div class="row justify-content-center row-gap-top-40">
                        <h2>Sequence dinucleotide calculation</h2>                
                </div>                
                <div class="row justify-content-left row-gap-top-40">
                        <div>Sequence length: @sqLength</div>
                </div>
                <div class="row justify-content-left row-gap-top-10">
                        <div>Sequence: @sqOut</div>
                </div>
        </div>
</body>

DinucMVC/DinucMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--        <title>@ViewBag.Title - My ASP.NET Application</title>-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="~/Content/Site.css">
</head>
<body>
        <div class="container-fluid">
                <div class="row row-gap-top-20">
                        <div class="col-sm-9 my-auto">
                                @Html.ActionLink("Dinucleotides calculation", "Index", "Home", new { style="color: black; font-size: 28px; padding: 20px 20px" })                                                        
                        </div>
                        <div class="col-sm-1 my-auto">
                                <li>@Html.ActionLink("Home", "Index", "Home", new { style = "color: black" })</li>
                        </div>
                        <div class="col-sm-1 my-auto">
                                <li>@Html.ActionLink("About", "About", "Home", new { style = "color: black" })</li>
                        </div>
                        <div class="col-sm-1 my-auto">
                                <li>@Html.ActionLink("Contacts", "Contacts", "Home", new { style = "color: black" })</li>
                        </div>
                </div>
        </div> 
                        
         <div class="container body-content" style="border:1px solid #cecece">
                @RenderBody()
        </div>
                
        <footer class="footer page-footer font-small black">
                 <div class="container text-center text-dark" style="position: ablolute; bottom:  0">
                        <a>&copy; @DateTime.Now.Year - Dinuc calculation</a>
                </div>
        </footer>
</body>
</html>